import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

enum language {
  English,
  Urdu,
}

class Language extends ChangeNotifier {
  language currentLang = language.Urdu;

  Map<String, String> english = {
    'welcome': 'Welcome Back',
    'admin': 'Admin',
    'customer': 'Customer',
    'seller': 'Seller',
    'quick_links': 'Quick Links',
    'designs': 'Designs',
    'categories': 'Categories',
    'categories_list': 'Categories List',
    'customers': 'Customers',
    'app_user': 'App User',
    'view_all': 'View All',
    'view all': 'View All',
    'user': ' User',
    'all users here': 'All users here',
    'all': "all",
    'password': 'Password',
    'email': 'email',
    'name': 'name',
    'phone': 'phone',
    'add user': 'add user',
    'edit user': 'edit user',
    'log': 'Log',
    'users activities': 'users activities',
    'share': 'Share',
    'activity': 'Activity',
    'profile': 'Profile',
    'edit your profile': 'Edit Your Profile',
    'change name': 'Change Name',
    'change password': 'Change Password',
    'new password': 'New Password',
    'confirm new password': 'Confirm New Password',
    'first name': 'First Name',
    'last name': 'Last Name',
    'dashboard': 'Dashboard',
    'contains all data': 'Contains All Data',
    'logout': "Logout",
    'logout from aness casting': 'Logout from Aness casting',
    'click on the logout button to proceed':
        'Click on the logout button to proceed',
    'cancel': 'Cancel',
    'your categories': 'Your Categories',
    'change your name and Password': 'Change your name and Password',
    'parent category': 'Parent Category',
    'delete': 'Delete',
    'category': 'Category',
    'all users activities': 'All Users Activities',
    'users': 'Users',
    'all users': 'All Users',
    'your designs': 'Your Designs',
    'design': 'Design',
    'home': 'Home',
    'logs': 'Logs',
    'load more': 'Load More',
    'edit': 'Edit',
    'add new user': 'Add New User',
    'filters': 'Filters',
    'clients': 'Clients',
    'welcome to anees casting': 'Welcome to Anees Casting',
    'manage users': 'Manage Users',
    'manage designs': 'Manage Designs',
    'by category': 'By Category',
    'by design': 'By Design',
    'add product': 'Add Product',
    'view products': 'View Products',
    'search here': 'Search Here',
    'title': 'Title ',
    'cat': 'Cat ',
    'length': 'Length ',
    'width': 'Width ',
    'date': 'Date ',
    'unit': 'Unit ',
    'yes': 'Yes',
    'no': 'No',
    'ok': 'OK',
    'error': 'Error',
    'select category': 'Select Category',
    'category name': 'Category Name',
    'add category': 'Add Category',
    'save changes': 'Save Changes',
    'edit design': 'Edit Design',
    'cat do you want to': 'Do you want to delete',
    'cat category?': 'Category?',
    'do you want to delete user?': 'Do you want to delete user?',
    'do you want to delete this product?':
        'Do you want to delete this product?',
    'parent category can\'t be deleted.': 'Parent Category can\'t be deleted.',
    'language': 'English',
    "empty fields":"Empty Fields",
    "please fill all fields":"Please Fill all Fields",
    "you can't assign": "You can't assign",
    'it have childs':'it has childs',
    'no products to show':'No Products to show',
    "product has been deleted": "Product has been deleted",
    'product will be deleted from the list permamently':'Product will be deleted from the list permamently',
    'product': 'Product',
    'list of products':'List of Products',
    'search product':'Search Product',
    'user data has been updated':'User Data has been Updated',
    'user has been added': 'User has been Added',
    'customer details':'Customer Details',
    'no customers to show':'No Customers to show',
    'user has been deleted':'User has been Deleted',
    'enter your email':'Enter Your Email',
    'forget password':'Forget Password',
    'password changed try login':'Password Changed, Try Login',
'must contains 6 character':'Must contains 6 character', 
'confirm password':'Confirm Password', 
'password is not matched': 'Password is not matched', 
'code':'Code',
"icorrect code":"Icorrect Code",
'enter the 6-digit code that is sent to your email address':'Enter the 6-digit code that is sent to your email address',
'code here':'Code here',
'invalid code':'Invalid Code',
'verify code':'Verify Code',
'enter password':'Enter Password',
'login':'Login',
'username has been changed':'Username has been changed',
"icorrect password":"Icorrect Password",
'password has been changed':'Password has been Changed',
'dear customer': 'Dear Customer',
'this category contains products cannot deleted':'This Category contains products cannot deleted',
'do you want to delete': 'Do You want to Delete',
'category has been deleted':'Category has been deleted',
'edit category': 'Edit Category',


  };
  Map<String, String> urdu = {
    'edit category':'کیٹگری میں تبدیلی کریں',
    'category has been deleted':'کیٹگری ڈیلیٹ ہو چکی ہے',
    'do you want to delete': 'کیا آپ اسے ڈلیٹ کرنا چاہتے ہیں',
    'this category contains products cannot deleted':'اس کیٹگری میں نئے ڈیزائنز ہیں اسے ڈیلیٹ نہیں کیا جاسکتا',
    'dear customer': 'معزز صارف',
    'password has been changed':'پاسورڈ تبدیل ہوچکا ہے',
    "icorrect password": 'غلط پاسورڈ',
    'username has been changed':"صارف کا نام تبدیل ہو چکا ہے",
    'login': 'لاگ ان',
    'enter password':'پاسورڈ لکھیں',
    'verify code':'کوڈ کی تصدیق کریں',
    'invalid code': 'غلط کوڈ',
    'code here':'کوڈ یہاں لکھیں',
    'enter the 6-digit code that is sent to your email address':'آپ کی ای میل پر بھیجا گیا 6 ہندسوں کا کوڈ درج کریں',
    'code': 'کوڈ',
    "icorrect code":'غلط کوڈ',
    'password is not matched': 'پاسورڈ غلط ہے',
    'confirm password': 'پاس ورڈ کی تصدیق کریں',
    'must contains 6 character': 'کم از کم 6 حروف',
    'password changed try login':'پاس ورڈ تبدیل٫ لاگ ان ہوں',
    'forget password': 'پاس ورڈ یاد نہیں',
    'enter your email':'اپنی ای میل لکھیں',
    'user has been deleted':'صارف ڈیلیٹ ہو چکا ہے',
    'no customers to show':'کوئی صارف موجود نہیں',
    'customer details': 'صارف کی تفصیل',
    'user has been added':'صارف کا اندراج ہو چکا ہے',
    'user data has been updated': 'صارف کا ڈیٹا تبدیل ہو چکا ہے',
    'Search Product':'تلاش کریں',
    'list of products': 'ڈیزائنز کی فہرست',
    'product': 'ڈیزائن',
    'product will be deleted from the list permamently':'ڈیزائن ہمیشہ کے لئے ڈیلیٹ ہو جائے گا',
    'no Products to show':'کوئی ڈیزائن موجود نہیں',
    "product has been deleted": 'ڈیزائن ڈیلیٹ ہو چکا ہے',
    "you can't assign": "آپ پیرنٹ کیٹگری نہیں دے سکتے",
    'it have childs':'',
    "empty fields":"خالی جگہیں",
    "please fill all fields": "تمام خالی جگہوں میں لکھیں",
    'welcome': 'خوش آمدید',
    'admin': 'ایڈمن',
    'customer': 'گاہک',
    'seller': 'سیلر',
    'quick_links': 'فوری رابطے',
    'designs': 'ڈیزائنز',
    'categories': 'اقسام',
    'categories_list': ' اقسام کی فہرست',
    'customers': 'گاہک',
    'app_user': 'ایپ صارف',
    'view_all': 'سب دیکھیں',
    'view all': 'سب دیکھیں',
    'all': "تمام",
    'user': ' صارف',
    'all users here': 'تمام صارف',
    'password': 'پاس ورڈ',
    'email': 'ای میل',
    'name': 'نام',
    'phone': 'موبائل نمبر',
    'edit user':'صارف میں تبدیلی کریں',
    'add user': 'صارف کا اندراج کریں',
    'log': 'لاگ',
    'users activities': 'صارف کی سرگرمیاں',
    'share': 'شیئر',
    'activity': 'سرگرمی',
    'profile': 'پروفائل',
    'edit your profile': 'اپنی پروفائل میں تبدیلی کریں',
    'change name': 'نام تبدیل کریں',
    'change password': 'پاس ورڈ تبدیل کریں',
    'new password': 'نیا پاس ورڈ',
    'confirm new password': 'نیا پاس ورڈ',
    'first name': 'پہلا نام',
    'last name': 'آخری نام',
    'dashboard': 'ڈیش بورڈ',
    'contains all data': 'تمام ریکارڈ',
    'logout': "لاگ آؤٹ",
    'logout from aness casting': 'انیس کاسٹنگ سے لاگ آؤٹ',
    'click on the logout button to proceed': 'بٹن دبائیں',
    'cancel': 'مؤخر کریں',
    'change your name and password': 'اپنا نام اور پاسورڈ تبدیل کریں',
    'cat list': 'کیٹگری لسٹ',
    'your categories': 'آپکی کیٹگری لسٹ',
    'add new category': 'نئی کیٹگری شامل کریں',
    'parent category': 'پیرنٹ کیٹگری',
    'category': 'کیٹگری',
    'cat': 'کیٹگری',
    'all users activities': 'صارفین کی سرگرمیاں',
    'delete': 'ڈیلیٹ',
    'users': 'صارفین',
    'all users': 'تمام صارفین',
    'your designs': 'آپکے ڈیزائنز',
    'design': 'ڈیزائن',
    'home': 'ہوم',
    'logs': 'سرگرمیاں',
    'load more': 'مزید',
    'edit': 'ایڈٹ',
    'add new user': 'نئے صارف کا اندراج کریں',
    'filters': 'فلٹر',
    'welcome to anees casting': 'انیس کاسٹنگ میں خوش آمدید',
    'manage users': 'تمام صارفین',
    'manage designs': 'تمام ڈیزائنز',
    'clients': 'گاہک',
    'by category': 'کیٹگری سے',
    'by design': 'ڈیزائن سے',
    'add product': 'ڈیزائن جمع کریں',
    'view products': 'ڈیزائن دیکھیں',
    'search here': 'تلاش کریں',
    'title': 'ٹائٹل',
    'length': 'لمبائی',
    'width': 'چوڑائی',
    'date': 'تاریخ',
    'unit': 'یونٹ',
    'yes': 'جی ہاں',
    'no': 'نہیں',
    'ok': 'اوکے',
    'category name': 'کیٹگری کا نام',
    'add category': 'کیٹگری جمع کریں',
    'save changes': 'تبدیلیاں محفوظ کریں',
    'edit design':'ڈیزائن میں تبدیلی کریں',
    'do you want to delete this product?':
        'کیا آپ اس ڈیزائن کو ڈیلیٹ کرنا چاہتے ہیں؟',
    'parent category can\'t be deleted.': 'پیرنٹ کیٹگری نہیں ہو سکتی',
    'language': 'اردو',
    'select category': 'کیٹگری منتخب کریں',
    'cat do you want to': 'کیا آپ',
    'delete user': 'صارف کو ڈیلیٹ کریں',
    'do you want to delete user?': 'کیا آپ صارف کو ڈیلیٹ کرنا چاہتے ہیں؟',
    'cat category?': 'کیا آپ صارف کو ڈیلیٹ کرنا چاہتے ہیں؟',
    'error': 'غلطی'
  };

  String get(String key) {
    print(key.toLowerCase());
    key = key.toLowerCase();
    var en = (english[key] != null ? english[key] : key);
    var ur = (urdu[key] != null ? urdu[key] : key);
    return currentLang == language.English ? en! : ur!;
  }

  void setLang(language lang) async {
    currentLang = lang;
    var shared = await SharedPreferences.getInstance();
    shared.setString('language', lang.toString());
    notifyListeners();
  }

  void defaultLang() async {
    var shared = await SharedPreferences.getInstance();
    if (shared.containsKey('language')) {
      var lang = shared.get('language');
      currentLang = lang == language.English.toString()
          ? language.English
          : language.Urdu;
      notifyListeners();
    }
  }
}
