// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyBYaZJ92YACuyJ30P8IHNU1CSwwdIrituA',
//     appId: '1:878643005566:web:e4fbe539a90ef611b9302f',
//     messagingSenderId: '878643005566',
//     projectId: 'aneescasting-ec184',
//     authDomain: 'aneescasting-ec184.firebaseapp.com',
//     storageBucket: 'aneescasting-ec184.appspot.com',
//     measurementId: 'G-E2Q3VQ5FLG',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBYhlmeIwLt0sdLzbvdUxU5JWFB-pgoa_Y',
//     appId: '1:878643005566:android:7342b8fa4c79067ab9302f',
//     messagingSenderId: '878643005566',
//     projectId: 'aneescasting-ec184',
//     storageBucket: 'aneescasting-ec184.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyALhfGim0xIMev0PqK3XgigZ2uZkiR5ZFY',
//     appId: '1:878643005566:ios:06d610dbf7933110b9302f',
//     messagingSenderId: '878643005566',
//     projectId: 'aneescasting-ec184',
//     storageBucket: 'aneescasting-ec184.appspot.com',
//     iosClientId: '878643005566-irb2u3ifp7iia8va0jjcdg4vkduvhtin.apps.googleusercontent.com',
//     iosBundleId: 'com.example.aneesCosting',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyALhfGim0xIMev0PqK3XgigZ2uZkiR5ZFY',
//     appId: '1:878643005566:ios:06d610dbf7933110b9302f',
//     messagingSenderId: '878643005566',
//     projectId: 'aneescasting-ec184',
//     storageBucket: 'aneescasting-ec184.appspot.com',
//     iosClientId: '878643005566-irb2u3ifp7iia8va0jjcdg4vkduvhtin.apps.googleusercontent.com',
//     iosBundleId: 'com.example.aneesCosting',
//   );
// }
